name: mluops_ci

on:
  push:
    branches: [master, r*]
    paths-ignore:
      - 'docs/**'
      - 'docker/**'
      - 'samples/**'
      - 'installer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - 'CONTRIBUTION.md'
      - 'CPPLINT.cfg'
      - 'LICENSE'
      - 'README.md'
      - 'requirements.txt'
      - '.github/workflows/mluops_all_system_ci.yaml'
      - '.github/workflows/daily.yaml'
  pull_request:
    branches: [master, r*]
    paths-ignore:
      - 'docs/**'
      - 'docker/**'
      - 'samples/**'
      - 'installer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - 'CONTRIBUTION.md'
      - 'CPPLINT.cfg'
      - 'LICENSE'
      - 'README.md'
      - 'requirements.txt'
      - '.github/workflows/mluops_all_system_ci.yaml'
      - '.github/workflows/daily.yaml'
    types: [opened, synchronize, reopened, review_requested, closed]

jobs:
  test:
    strategy:
      matrix:
        runner: [mlu370-m8]
        mlu_ops_version : [v1.1.0]
    runs-on: [yellow]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: run_mlu_ops_ci
        run: >
          bash .github/ci_script/mlu-ops-ci_script.sh

  recheck:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Trigger Pull Request checks
        run: |
          # Get the numbers of all open Pull Requests.
          PR_LIST=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | jq -r '.[].number')

          # Iterate through each Pull Request and trigger checks again.
          for PR_NUMBER in $PR_LIST; do
            echo "Triggering checks for PR #$PR_NUMBER"
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers"
          done
