name: mluops_ci

on:
  push:
    branches: [master, r*]
    paths-ignore:
      - 'docs/**'
      - 'docker/**'
      - 'samples/**'
      - 'installer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - 'CONTRIBUTION.md'
      - 'CPPLINT.cfg'
      - 'LICENSE'
      - 'README.md'
      - 'requirements.txt'
      - '.github/workflows/mluops_all_system_ci.yaml'
      - '.github/workflows/daily.yaml'
  pull_request:
    branches: [master, r*]
    paths-ignore:
      - 'docs/**'
      - 'docker/**'
      - 'samples/**'
      - 'installer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - 'CONTRIBUTION.md'
      - 'CPPLINT.cfg'
      - 'LICENSE'
      - 'README.md'
      - 'requirements.txt'
      - '.github/workflows/mluops_all_system_ci.yaml'
      - '.github/workflows/daily.yaml'
    types: [closed]

jobs:
  test:
    strategy:
      matrix:
        runner: [mlu370-m8]
        mlu_ops_version : [v1.1.0]
    runs-on: [yellow]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: run_mlu_ops_ci
        run: >
          bash .github/ci_script/mlu-ops-ci_script.sh

  post-merge:
    if: github.event.pull_request.merged == true
    runs-on: [yellow]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Fetch master
        run: git fetch origin master

      - name: Check rebase
        run: |
          if git log --oneline origin/master..HEAD; then
            echo "PR is rebased."
          else
            echo "PR is not rebased. Please rebase your changes onto master."
            exit 1
          fi
